spring:  
    application: 
        name: BootIOCProj07-YML
  
#PErsonal Information
per:  
   info:
     id: 1001
     name: "raja"
     addrs: "hyd"
     email: "raja@rani.com"
     mobileNo: 9999999
     favColors:
         - red
         - green
         - yellow 
     friends:
         - kiran
         - ramesh
         - suresh 
     phoneNumbers:
         - 9999999
         - 8888888
         - 7777777 
     phone-numbers: [11111,33333,6666666]

     idDetails:
           aadhar :  4545454
           voterid : 454545611
           panNo : 4546655
     company:
          cid: 1001
          cname: HCL
          location: Delhi
          pinCode: 5454565

